cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.add_cart, name='add_cart'),
    path('remove/<int:product_id>/', views.remove, name='remove_cart'),
]

coupon/urls.py
from django.urls import path
from . import views

app_name = 'coupon'

urlpatterns = [
    path('apply/', views.coupon_apply, name='apply'),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _

urlpatterns = i18n_patterns(
    path(_('admin/'), admin.site.urls),
    path(_('cart/'), include('cart.urls', namespace='cart')),
    path(_('orders/'), include('orders.urls', namespace='orders')),
    path(_('payments/'), include('payments.urls', namespace='payment')),
    path(_('coupons/'), include('coupon.urls', namespace='coupon')),
    path('rosetta/', include('rosetta.urls')),
    path('', include('shop.urls', namespace='shop')),

)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views
from django.utils.translation import gettext_lazy as _

app_name = 'orders'
urlpatterns = [
    path(_('create/'), views.order_create, name='order_create'),
    path('admin/order/<int:order_id>/',
         views.admin_order_detail, name='admin_order_detail'),
    path('admin/order/<int:order_id>/pdf/',
         views.admin_order_pdf, name='admin_order_pdf'),
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'
urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:catagory_slug>/', views.product_list,
         name='product_list_by_catagory'),
    path('<int:id>/<slug:slug>/', views.product_details, name='product_details')
]

cart/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CarAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
        choices=PRODUCT_QUANTITY_CHOICES,
        coerce=int,
        label=_('Quantity'),
    )

    override = forms.BooleanField(required=False,
                                  initial=False,
                                  widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CarAddProductForm
from coupon.forms import CouponApplyForm
from shop.recommender import Recommender


@require_POST
def add_cart(request, product_id):
    '''
    method for adding items to the cart
    '''
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CarAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 override_quantity=cd['override'])

    return redirect('cart:cart_detail')


@require_POST
def remove(request, product_id):
    '''
    method for removing an item from the cart
    '''
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    '''
    method for showing details of the cart
    '''
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CarAddProductForm(initial={
            'quantity': item['quantity'],
            'override': True
        })
    coupon_apply_form = CouponApplyForm()

    # recommendation in the cart
    r = Recommender()
    cart_products = [item['product'] for item in cart]
    recommended_products = r.suggest_products_for(cart_products, max_result=4)
    return render(request, 'cart/details.html', {'cart': cart, 'coupon_apply_form': coupon_apply_form, 'recommended_products': recommended_products})

cart/templates/cart/details.html
{% extends 'shop/base.html' %}
{% load i18n %}
{% load static %}

{% block title %} {% trans "Shopping cart" %} {% endblock title %}

{% block content %}
<h1>{% trans "Your shopping Cart" %}</h1>
<table class="cart">
    <thead>
        <tr>
            <th>{% trans "Image" %}</th>
            <th>{% trans "Product" %}</th>
            <th>{% trans "Quantity" %}</th>
            <th>{% trans "remove" %}</th>
            <th>{% trans "unit Price" %}</th>
            <th>{% trans "Price" %}</th>
        </tr>
    </thead>
    <tbody>
        {% for item in cart %}
        {% with product=item.product %}
        <tr>
            <td>
                <a href="{{ product.get_absolute_url }}">
                    <img src="{% if product.image %} {{ product.image.url }} 
                    {% else %} {% static 'img/no_image.png' %} {% endif %}">
                </a>
            </td>
            <td>{{ product.name }}</td>
            <td>
                <form action="{% url 'cart:add_cart' product.id %}" method="POST">
                    {{ item.update_quantity_form.quantity }}
                    {{ item.update_quantity_form.override }}
                    <input type="submit" value="{% trans 'Update' %}">
                    {% csrf_token %}
                </form>
            </td>
            <td>
                <form action="{% url 'cart:remove_cart' product.id %}" method="POST">
                    <input type="submit" value="{% trans 'Remove' %}">
                    {% csrf_token %}
                </form>
            </td>
            <td>$ {{ item.price }}</td>
            <td>$ {{ item.total_price }}</td>
        </tr>
        {% endwith %}
        {% endfor %}
        <tr class="total">
            <td>{% trans "Total" %}</td>
            <td colspan="4"></td>
            <td class="num">${{ cart.get_total_price }}</td>
        </tr>
        {% if cart.coupon %}
        <tr class="subtotal">
            <td>{% trans "Subtotal" %}</td>
            <td colspan="4"></td>
            <td class="num">$ {{ cart.get_total_price|floatformat:2}}</td>
        </tr>
        <tr>
            <td>
                "{{ cart.coupon.code }}" coupon
                {{ cart.coupon.discount }}% off
            </td>
            <td colspan="4"></td>
            <td class="num neg">
                - ${{ cart.get_discount|floatformat:2 }}
            </td>
        </tr>
        {% endif %}
        <tr class="total">
            <td>{% trans "Total" %}</td>
            <td colspan="4"></td>
            <td class="num">${{ cart.get_total_price_after_discount|floatformat:2 }}</td>
        </tr>
    </tbody>
</table>

{% if recommended_products %}
<div class="recommendations cart">
    <h3>{% trans "People also likes" %}</h3>
    {% for p in recommended_products %}
    <div class="item">
        <a href="{{ p.get_absolute_url }}">
            <img src="{% if p.image %} {{ p.image.url }} {% else %} {% static 'img/no_image.png' %} {% endif %}">
        </a>
        <p><a href="{{ p.get_absolute_url }}"> {{ p.name }}</a></p>
    </div>
    {% endfor %}
</div>
{% endif %}



<p class="text-right">
<p>{% trans "Apply a coupon" %}</p>
<form action="{% url 'coupon:apply' %}" method="POST" style="margin-bottom: 50px;">
    {{ coupon_apply_form }}
    <input type="submit" value="{% trans 'Apply' %}">
    {% csrf_token %}
</form>

<a href="{% url 'shop:product_list' %}" class="button light">{% trans "Continue Shopping" %}</a>
<a href="{% url 'orders:order_create' %}" class="button">{% trans "Checkout" %}</a>
</p>
{% endblock content %}